name: Flutter CI

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on tags like v1.0.0
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x" # Use a specific Flutter version or '3.x' for the latest stable 3.x

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Create keystore file
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.STORE_FILE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
        shell: bash

      - name: Create key.properties
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        shell: bash

      - name: Build Android (Release)
        if: startsWith(github.ref, 'refs/tags/')
        run: flutter build apk --release

      - name: Rename APK
        if: startsWith(github.ref, 'refs/tags/')
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/correcteur_flottant-${{ github.ref_name }}.apk
        shell: bash

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/correcteur_flottant-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
