name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version or '3.x' for the latest stable 3.x

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze



      - name: Create keystore file
        run: echo "${{ secrets.STORE_FILE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
        shell: bash

      - name: Create key.properties
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        shell: bash

      - name: Build Android (Release)
        run: flutter build apk --release
